# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Shotbud shot timer for Apple Watch
email: cweiland2808@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Shotbud is a full shot timer experience made for enthusiats and professionals alike. Using the sensors in Apple Watch, Shotbud can detect your shots and track your performance during live or dry fire.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
community_url: ""
support_url: ""

includes_dir:    _components
uploads_dir: "uploads/"

# Permalink structures and stuff
permalink: pretty
collections:

# Build settings
markdown: kramdown

# Related posts
related:
  max_count: 2

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-assets
  - jekyll-sitemap

# FrontMatter defaults
defaults:
  -
    scope:
      path: ""      # empty string for all files
      type: posts   # limit to posts
    values:
      is_post: true # automatically set is_post=true for all posts
  -
    scope:
      path: ""
      type: docs
    values:
      layout: 'article'
  -
    scope:
      path: ""
      type: categories
    values:
      _hide_content: true
  -
    scope:
      path: ""
      type: tags
    values:
      layout: 'tags'
      _hide_content: true

# Files/dirs to exclude from the build
exclude:
  - Dockerfile
  - Gemfile*
  - .gitignore
  - package.json
  - README.md
  - deploy.sh
  - server.js
  - node_modules
  - test
  - vendor

# sass options
sass:
    style: compressed

assets:
  compress:
    css: true
    js: true
  baseurl: /assets
  cache: false
  digest: false
  cachebusting: false
  sources:
    - css
    - fonts
    - images
    - js

jekyll-archives:
  enabled:
  - tags
  layout: 'list'
  permalinks:
    tag: '/tag/:name/'
